### PR TITLE
Anti quorum and early fail quorum decisions

### LINKED ISSUE #155: Implement Quorum-based early fail for Strongly Reach

### PR DESCRIPTION
**Pull request by Tjofil**
This PR introduces a simple concept of `Anti Quorum` denoting a threshold that has to be crossed by validators voting negatively, in order to guarantee a negative voting decision. This threshold is essentially a complement Quorum's complement in the sum of total validator stake. 
- Stake tests have been extended to include and test AntiQuorum.
- `stronglyReachableByQuorum` now leverages the fact that the majority of decision votes in a Sonic Consensus fail, stopping the vote when Anti Quorum is reached. To optimize the approach further, the frame bases are traversed in a descending order of their respective validator stake, making the early-fail and early-succeed decisions occurr with minimal number of `StronglyReach` calls.

Testing done:
All unit tests pass
Client build with the PR branch passes epochs [1, 1100] and [6720, 6970] and produces a correct head.

### CODE REVIEW

File: consensus/stake.go [hunk 1]
```diff
@@ -38,18 +37,19 @@ func newWeightCounter(vv Validators) *WeightCounter {
...
 }
 
-// CountVoteByID validator and return true if it hadn't counted before.
 func (s *WeightCounter) CountVoteByID(v ValidatorID) bool {
 	validatorIdx := s.validators.GetIdx(v)
 	return s.CountVoteByIndex(validatorIdx)
 }
 
-// CountVoteByIndex validator and return true if it hadn't counted before.
+// CountVoteByIndex increases the vote sum by validator's weight if the validator hasn't voted before, returning the status of the vote
```
Comment (kmeeth) [inline consensus/stake.go:52]: nit: I would perhaps favor long forms of negative predicates (has not instead of hasn't). Leave it be if such forms are prominent in the whole codebase.

File: consensus/stake.go [hunk 2]
```diff
@@ -24,12 +24,11 @@ type (
 		validators   Validators
 		alreadyVoted []bool // ValidatorIdx -> bool
 
-		quorum Weight
-		sum    Weight
+		quorum, antiQuorum Weight
```
Comment (kmeeth) [inline consensus/stake.go:27]: nit: should these not be somehow lined up?

**Review by kmeeth — APPROVED** [review]
possible nit: I like the changes, they are readable and understandable. Here is just a little food for thought:
As it is now, we have a lot of functions that are analogous to existing functions, but with "anti" semantics. Maybe we can think about whether there is an elegant way to merge these functions into fewer functions that are parametrized. For now it seems to me this might hurt readability, but if someone has an idea how this could be done in an equally readable way, it might be worth exploring. Nice job either way.

**Review by aksonic — APPROVED** [review]

**Review by psubotic — APPROVED** [review]
